# constants

FIELD_X_MIN = -2000
FIELD_X_MAX = 2000
FIELD_Y_MIN = -2000
FIELD_Y_MAX = 2000
GOAL_Y_MIN = -500
GOAL_Y_MAX = 500
CENTRAL_CIRCLE_RADIUS = 500
SMALL_AREA_X_MAX = -1000
SMALL_AREA_Y_MIN = -1000
SMALL_AREA_Y_MAX = 1000



LATERAL_RIGHT_ACTION_AREA_X_MIN = FIELD_X_MIN
LATERAL_RIGHT_ACTION_AREA_X_MAX = FIELD_X_MAX
LATERAL_RIGHT_ACTION_AREA_Y_MIN = FIELD_Y_MIN
LATERAL_RIGHT_ACTION_AREA_Y_MAX = GOAL_Y_MIN

LATERAL_LEFT_ACTION_AREA_X_MIN = FIELD_X_MIN
LATERAL_LEFT_ACTION_AREA_X_MAX = FIELD_X_MAX
LATERAL_LEFT_ACTION_AREA_Y_MIN = GOAL_Y_MAX
LATERAL_LEFT_ACTION_AREA_Y_MAX = FIELD_Y_MAX

CENTRAL_DEFENDER_ACTION_AREA_X_MIN = FIELD_X_MIN
CENTRAL_DEFENDER_ACTION_AREA_X_MAX = CENTRAL_CIRCLE_RADIUS
CENTRAL_DEFENDER_ACTION_AREA_Y_MIN = SMALL_AREA_Y_MIN + (FIELD_Y_MIN - SMALL_AREA_Y_MIN)/2
CENTRAL_DEFENDER_ACTION_AREA_Y_MAX = SMALL_AREA_Y_MAX + (FIELD_Y_MAX - SMALL_AREA_Y_MAX)/2

GOALKEEPER_ACTION_AREA_X_MIN = FIELD_X_MIN
GOALKEEPER_ACTION_AREA_X_MAX = SMALL_AREA_X_MAX
GOALKEEPER_ACTION_AREA_Y_MIN = SMALL_AREA_Y_MIN
GOALKEEPER_ACTION_AREA_Y_MAX = SMALL_AREA_Y_MAX

# rival goal
RIVAL_GOAL = {'x':2000, 'y':-300}

RIVAL_ACTION_AREA_X_MIN = 1000
RIVAL_ACTION_AREA_X_MAX = 2000
RIVAL_ACTION_AREA_Y_MAX = 1000
RIVAL_ACTION_AREA_Y_MIN = -1000

LATERAL_RIGHT_ATACKING_POSITION_X = 1000
LATERAL_RIGHT_ATACKING_POSITION_Y = -1000
LATERAL_RIGHT_DEFENDING_POSITION_X = -1000
LATERAL_RIGHT_DEFENDING_POSITION_Y = -1000

LATERAL_LEFT_ATACKING_POSITION_X = 1000
LATERAL_LEFT_ATACKING_POSITION_Y = 1000
LATERAL_LEFT_DEFENDING_POSITION_X = -1000
LATERAL_LEFT_DEFENDING_POSITION_Y = 1000

CENTRAL_DEFENDER_ATACKING_POSITION_X = 0
CENTRAL_DEFENDER_ATACKING_POSITION_Y = 0
CENTRAL_DEFENDER_DEFENDING_POSITION_X = -1500
CENTRAL_DEFENDER_DEFENDING_POSITION_Y = 0

STRICKER_ATACKING_POSITION_X = 1000
STRICKER_ATACKING_POSITION_Y = 0
STRICKER_DEFENDING_POSITION_X = 0
STRICKER_DEFENDING_POSITION_Y = 0

GOALKEEPER_ATACKING_POSITION_X = -1900
GOALKEEPER_ATACKING_POSITION_Y = 0
GOALKEEPER_DEFENDING_POSITION_X = -2000
GOALKEEPER_DEFENDING_POSITION_Y = 0
